training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 1000001
  snapshot_freq: 100000
  save_freq: 10000
  num_workers: 8

sampling:
#  sample_way: 'DDPM'
  cfg_scale: 4.0

data:
 ## cifar10
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  random_flip: true
  num_classes: 10
  sigma_data: 0.5

model:
  model_name: 'EDM_AdaGN_Unet_attention'
  hidden_dim: 64
  ngf: 128
  embeding_size: 512
#  num_groups: 32
  num_res_blocks: 2
  class_dropout_prob: 0.1
  attention_resolutions: [16, 8]

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  warmup_steps: 5000
  lr: 0.0001
  beta1: 0.9
  amsgrad: false