training:
  batch_size: 128
  n_epochs: 50000
  n_iters: 500001
  ngpu: 1
  snapshot_freq: 10000

sampling:
  sample_way: 'SMLD'
  cfg_scale: 4.0
  # num_sampling_steps: 150

data:
  ## mnist
  # dataset: "MNIST"
  # image_size: 28
  # channels: 1
  # logit_transform: false
  # random_flip: false

 ## cifar10
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  random_flip: true
  num_classes: 10

model:
  sigma_begin: 50
  sigma_end: 0.01
  hidden_dim: 64
  # 1000 for DDPM, 10 for SMLD is suggested.
  num_timesteps: 20
  learn_sigma: false
  predict_xstart: true
  ngf: 64
  embeding_size: 512
  num_groups: 32
  class_dropout_prob: 0.1

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
